CREATE TABLE T_STUDENT(
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL ,
  SEX VARCHAR(255) NOT NULL ,
  CLASSID VARCHAR(100) NOT NULL,
  STUDENTCARDNO VARCHAR(255) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;