spring:
  datasource:
    url: jdbc:mysql://192.168.94.150:3306/maps?useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis: 
  mapper-locations: classpath*:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity
    