CREATE TABLE T_USER(
  USERID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(255) NOT NULL ,
  PASSWORD VARCHAR(255) NOT NULL ,
  ROLEID VARCHAR(100) NOT NULL,
  CREATE_DATE TIMESTAMP NOT NULL,
  CREATE_BY   VARCHAR(100) NOT NULL,
  UPDATE_DATE TIMESTAMP not NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_BY  VARCHAR(100) NOT NULL,
  STATUS VARCHAR(255) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;












